# Generated by Django 3.2 on 2024-07-23 17:40

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[reviews.validators.validate_year_not_future], verbose_name='Год выпуска'),
        ),
    ]
