# Generated by Django 3.2 on 2024-07-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240716_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='riview',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текс'),
        ),
    ]
